[package]
name = "todo-server"
version = "0.1.0"
authors = ["Filipe"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
num_cpus = "1"

[dev-dependencies]
bytes="1"